name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: install dependencies
        run: npm ci
      - name: run build
        run: npm run build
      - name: lint
        run: npm run lint
      - name: test 
        run: npm test
